version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    networks:
      vnet:
        ipv4_address: 10.6.0.100
  client_1:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - SRV_ADDR=10.6.0.100
    networks:
      vnet:
        ipv4_address: 10.6.0.101
  client_2:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    environment:
      - SRV_ADDR=10.6.0.100
    networks:
      vnet:
        ipv4_address: 10.6.0.102
  client_3:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5003:5001"
    environment:
      - SRV_ADDR=10.6.0.100
    networks:
      vnet:
        ipv4_address: 10.6.0.103

networks:
  vnet:
    ipam:
      config:
        - subnet: 10.6.0.0/16
