version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      vnet:
        ipv6_address: 2001:db8::1
  client_1:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    networks:
      vnet:
        ipv6_address: 2001:db8::101
  client_2:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    networks:
      vnet:
        ipv6_address: 2001:db8::102
  client_3:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    networks:
      vnet:
        ipv6_address: 2001:db8::103

networks:
  vnet:
    ipam:
      config:
        - subnet: 10.6.0.0/16
